empty if/else-expression inspection with quick fixes
i582/vlang-idea pull request #125
Opened 2022-10-10 16:27 UTC by MohammadMD1383

2022-10-10 17:36 UTC, MohammadMD1383 commented
#90

2022-10-11 07:00 UTC, MohammadMD1383 commented
I don't know how to make it better😅, could you help me please? @i582

2022-10-11 08:59 UTC, i582 commented
> I don't know how to make it better😅, could you help me please? @i582

Add tests 😄

2022-10-11 09:06 UTC, i582 commented
I'm not sure if it's worth highlighting them as unused, let's do it like in Kotlin and other languages, will it be a warning for the `if` or `else` keyword?

<img width="234" alt="Снимок экрана 2022-10-11 в 13 03 40" src="https://user-images.githubusercontent.com/51853996/195047285-5fb8aeed-c3a9-4c72-83d4-f937da42fd61.png">

And it seems that the inspection message is also not always correct, because `if` is not always an expression, it can be a statement. I also suggest changing the message as in Kotlin above.

2022-10-11 09:10 UTC, i582 commented
Let's change the name of the group to "Probable bugs" like in Kotlin. It's good practice to see how it's done for other languages.

2022-10-11 09:13 UTC, i582 requested changes

2022-10-11 13:04 UTC, i582 requested changes

2022-10-11 13:04 UTC, i582 commented on src/main/resources/inspectionDescriptions/VlangControlFlowWithEmptyBodiesInspection.html
> +Reports empty if expressions in the code
Doesn't comply with the new checks

2022-10-11 13:04 UTC, i582 commented on src/main/kotlin/org/vlang/ide/inspections/probableBugs/VlangControlFlowWithEmptyBodiesInspection.kt
> +            val element = descriptor.psiElement!!
I usually don't use `!!` as this is a potential NPE, it seems better to do `?: return` here and below

2022-10-11 13:04 UTC, i582 commented on src/main/kotlin/org/vlang/ide/inspections/probableBugs/VlangControlFlowWithEmptyBodiesInspection.kt
> +        override fun getName() = "Remove empty statement"
There is no need to override `getName`, it calls `getFamilyName` by default, so `override fun getFamilyName() = "Remove empty statement"` is enough

2022-10-11 13:04 UTC, i582 commented
And tests of course 😄

2022-10-11 17:15 UTC, MohammadMD1383 commented on src/main/kotlin/org/vlang/ide/inspections/probableBugs/VlangControlFlowWithEmptyBodiesInspection.kt
> +        override fun getName() = "Remove empty statement"
Thanks for the tip! I didn't know that :)

2022-10-13 16:32 UTC, i582 commented on src/test/resources/inspections/probableBugs/ctrlflow_with_empty_body.after.v
> +	if true {
Seems to be a formatting problem.

2022-10-13 16:34 UTC, MohammadMD1383 commented on src/test/resources/inspections/probableBugs/ctrlflow_with_empty_body.after.v
> +	if true {
should I handle it manually or someway trigger the formatter?

2022-10-13 16:39 UTC, i582 commented on src/test/resources/inspections/probableBugs/ctrlflow_with_empty_body.after.v
> +	if true {
I think if you have a plugin installed in the IDE where you are developing, then calling the formatter will do everything for you

2022-10-13 16:44 UTC, MohammadMD1383 commented on src/test/resources/inspections/probableBugs/ctrlflow_with_empty_body.after.v
> +	if true {
sorry for the mistake, I misunderstood your review 😂.

2022-10-13 16:53 UTC, MohammadMD1383 commented
Seems that the IDE is replacing 4-spaces with tabs after applying quick-fix

2022-10-13 17:00 UTC, i582 commented on src/test/resources/inspections/probableBugs/ctrlflow_with_empty_body.v
> +    <warning descr="For has empty body">for</warning> el in arr {
Please add tests with a non-empty body and a body with a comment. Ideally, tests should cover all possible cases.

2022-10-13 17:01 UTC, i582 commented
And rename PR

2022-10-14 07:01 UTC, i582 approved these changes

2022-10-14 07:02 UTC, merged

2022-10-14 07:03 UTC, i582 commented
Thank you, this is a great contribution!